[features]
seeds = false
skip-lint = false
[programs.devnet]
token_presale = "3nCqy8nALeMvFPG8Rou5xL7UVcrRyz7QEUVHgV26ATP8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
